import os

#from . import test_novitus_receipt, test_novitusxml_receipt

NOVITUS_URL = os.environ.get('NOVITUS_URL', 'hwgrep://.*Novitus.*')
NOVITUS_XML_URL = os.environ.get('NOVITUS_XML_URL', 'hwgrep://.*Novitus.*')

simple_receipt = {
 'cashier': 'Mitchell Admin',
 'checkout_id': 1,
 'client': None,
 'currency': {'decimals': 2,
              'id': 17,
              'name': 'PLN',
              'position': 'after',
              'rate': 4.1005,
              'rounding': 0.01,
              'symbol': 'zł'},
 'name': '00014-001-0001',
 'orderlines': [{'discount': '0%',
                 'price': 800.4,
                 'product_description_sale': '160x80cm, with large legs.',
                 'product_name': 'Customizable Desk (CONFIG) (Aluminium, '
                                 'White)',
                 'quantity': 2,
                 'taxes': [{'amount': 23,
                            'amount_type': 'percent',
                            'children_tax_ids': [],
                            'id': 1,
                            'include_base_amount': False,
                            'name': 'VAT-23%',
                            'price_include': True}],
                 'unit_name': 'Units'},
                {'discount': '0%',
                 'price': 12.5,
                 'product_description_sale': False,
                 'product_name': 'Office Chair Black',
                 'quantity': 1,
                 'taxes': [{'amount': 23,
                            'amount_type': 'percent',
                            'children_tax_ids': [],
                            'id': 1,
                            'include_base_amount': False,
                            'name': 'VAT-23%',
                            'price_include': True}],
                 'unit_name': 'Units'},
                {'discount': '0%',
                 'price': 450,
                 'product_description_sale': 'Desk combination, black-brown: '
                                             'chair + desk + drawer.',
                 'product_name': 'Desk Combination',
                 'quantity': 1,
                 'taxes': [{'amount': 23,
                            'amount_type': 'percent',
                            'children_tax_ids': [],
                            'id': 1,
                            'include_base_amount': False,
                            'name': 'VAT-23%',
                            'price_include': True}],
                 'unit_name': 'Units'}],
 'paymentlines': [{'amount': 1000,
                   'payment_method': 'Cash',
                   'pfp_fiscal_id': 'cash'},
                  {'amount': 1063.3,
                   'payment_method': 'Bank',
                   'pfp_fiscal_id': 'cash'}],
 'total_with_tax': 2063.3} 

discounted_receipt_with_client = {
    'cashier': 'Mitchell Admin',
    'checkout_id': 1,
    'client': {
        'address': 'Staroprzygodzka 117, 63-400, Ostrów Wielkopolski, Poland',
        'barcode': False,
        'city': 'Ostrów Wielkopolski',
        'country_id': [178, 'Poland'],
        'email': 'serwisit@litexservice.pl',
        'id': 43,
        'mobile': False,
        'name': 'Litex Service Sp. z o.o.',
        'phone': False,
        'property_account_position_id': False,
        'property_product_pricelist': [1, 'Public Pricelist (PLN)'],
        'state_id': False,
        'street': 'Staroprzygodzka 109',
        'vat': 'PL6220006775',
        'write_date': '2020-06-29 13:39:25',
        'zip': '63-400'
    },
    'currency': {
        'decimals': 2,
        'id': 17,
        'name': 'PLN',
        'position': 'after',
        'rate': 4.1005,
        'rounding': 0.01,
        'symbol': 'zł'
    },
    'name': 'Order 00002-006-0002',
    'orderlines': [{
        'discount': '0%',
        'price': 147,
        'product_description_sale': False,
        'product_name': 'Corner Desk Right Sit free',
        'quantity': 1,
        'taxes': [{'amount': 0,
                'amount_type': 'percent',
                'children_tax_ids': [],
                'id': 8,
                'include_base_amount': False,
                'name': 'VAT-ZW',
                'price_include': False}],
        'unit_name': 'Units'
    }, {
        'discount': '23%',
        'price': 15.120000000000001,
        'product_description_sale': False,
        'product_name': 'Cabinet with Doors 8%',
        'quantity': 2,
        'taxes': [{'amount': 8,
                'amount_type': 'percent',
                'children_tax_ids': [],
                'id': 3,
                'include_base_amount': False,
                'name': 'VAT-8%',
                'price_include': False}],
        'unit_name': 'Units'
    }, {
        'discount': '17%',
        'price': 60000,
        'product_description_sale': 'Three Seater Sofa with Lounger '
                                    'in Steel Grey Colour',
        'product_name': 'Three-Seat Sofa',
        'quantity': 1,
        'taxes': [{'amount': 23,
                'amount_type': 'percent',
                'children_tax_ids': [],
                'id': 1,
                'include_base_amount': False,
                'name': 'VAT-23%',
                'price_include': True}],
        'unit_name': 'Units'
    }],
    'paymentlines': [{'amount': 49970.28, 'payment_method': 'Bank', 'pfp_fiscal_id': 'transfer'}],
    'total_with_tax': 49970.28
} 
